resources:
- namespace.yaml
#- secret.yaml
- ../channelchannel.yaml
- placementrule-a-us1.yaml
- placementrule-a-us2.yaml
- placementrule-a-eu1.yaml
- placementrule-a-eu3.yaml
- placementrule-g-eu3.yaml
- placementrule-a-uw1.yaml
- placementrule-az-cus.yaml
- subscription-provider-a-us1.yaml
- subscription-provider-a-us2.yaml
- subscription-provider-a-eu1.yaml
- subscription-provider-a-eu3.yaml
- subscription-provider-g-eu3.yaml
- subscription-provider-a-uw1.yaml
- subscription-provider-az-cus.yaml
- application.yaml
